spring:
  datasource:
    account:
      url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      driver-class-name: org.h2.Driver
      username: sa
      password:
    balance:
      url: jdbc:h2:mem:balancedb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    show-sql: true
    format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8081

