name: Infrastructure and App Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  BUCKET_NAME: "anderson-account-balance-state" 
  AWS_REGION: "us-east-1"
  APP_NAME: "anderson-account-balance-app"

jobs:
  infra-and-app:
    runs-on: ubuntu-latest
    steps:
      #[Step0] 
      - name: Checkout code
        uses: actions/checkout@v4

      #[Step1] 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #gh-secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #gh-secrets
          aws-region: ${{ env.AWS_REGION }}

     #[Step2] 
      - name: Ensure S3 Bucket exists
        run: |
          if ! aws s3api head-bucket --bucket "${{ env.BUCKET_NAME }}" 2>/dev/null; then
            aws s3api create-bucket --bucket "${{ env.BUCKET_NAME }}" --region ${{ env.AWS_REGION }}
          fi

      #[Step3] 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./infra

       #[Step4] 
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      #[Step5] 
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG $ECR_REGISTRY/${{ env.APP_NAME }}:latest
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:latest

       #[Step6] 
      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster accountbalance-api-cluster --service accountbalance-api-service --force-new-deployment